# -*- coding: utf-8 -*-
"""IPL_perfromance_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1axwv1SiHodWRq5YaRAUH34U5npSPE6rX
"""

!pip install plotly pandas numpy ipywidgets -q

import pandas as pd
import numpy as np
import plotly.graph_objects as go
import plotly.express as px
from plotly.subplots import make_subplots
import ipywidgets as widgets
from IPython.display import display, HTML
import warnings
warnings.filterwarnings('ignore')

print("✅ All libraries imported successfully!")

print("📥 Downloading Men's IPL dataset from Cricsheet...")
!wget -q https://cricsheet.org/downloads/ipl_male_csv2.zip
!unzip -q ipl_male_csv2.zip -d ipl_data

try:
    # Try to find the CSV file in the extracted folder
    import os
    import glob

    # Look for CSV files
    csv_files = glob.glob('ipl_data/*.csv')

    if csv_files:
        # Load the first CSV file (usually the main one)
        df = pd.read_csv(csv_files[0])
        print(f"✅ Data loaded successfully! Total rows: {len(df)}")
        print(f"📊 Columns available: {df.columns.tolist()}")
        print(f"\n📅 Seasons covered: {sorted(df['season'].unique()) if 'season' in df.columns else 'N/A'}")
        print(f"🏏 Teams: {sorted(df['batting_team'].unique()[:5]) if 'batting_team' in df.columns else 'N/A'}...")
    else:
        raise FileNotFoundError("No CSV files found")

except Exception as e:
    print(f"⚠️ Error loading data: {e}")
    print("Creating sample data for demonstration...")
    # Create sample data for demonstration
    df = pd.DataFrame({
        'match_id': range(1000),
        'season': np.random.choice(['2020', '2021', '2022', '2023'], 1000),
        'batting_team': np.random.choice(['Chennai Super Kings', 'Mumbai Indians', 'Royal Challengers Bangalore'], 1000),
        'bowling_team': np.random.choice(['Chennai Super Kings', 'Mumbai Indians', 'Royal Challengers Bangalore'], 1000),
        'ball': np.random.uniform(0.1, 20.0, 1000),
        'batter': np.random.choice(['MS Dhoni', 'Rohit Sharma', 'Virat Kohli', 'Faf du Plessis'], 1000),
        'bowler': np.random.choice(['Jasprit Bumrah', 'Ravindra Jadeja', 'Rashid Khan'], 1000),
        'runs_off_bat': np.random.choice([0, 1, 2, 3, 4, 6], 1000),
        'extras': np.random.choice([0, 1, 2], 1000, p=[0.8, 0.15, 0.05]),
        'wicket_type': np.random.choice([None, 'caught', 'bowled', 'lbw'], 1000, p=[0.9, 0.05, 0.03, 0.02])
    })

def clean_data(df):
    """Clean and prepare the data"""
    df = df.copy()

    # Create over number from ball column
    if 'ball' in df.columns:
        df['over'] = df['ball'].astype(int) + 1

    # Calculate total runs
    df['total_runs'] = df['runs_off_bat'] + df['extras']

    # Create phase column
    df['phase'] = pd.cut(df['over'],
                         bins=[0, 6, 15, 21],
                         labels=['Powerplay (1-6)', 'Middle (7-15)', 'Death (16-20)'])

    # Create wicket indicator
    df['is_wicket'] = df['wicket_type'].notna().astype(int)

    # Identify bowler type (simplified - you can enhance this)
    left_arm_spinners = ['Ravindra Jadeja', 'Axar Patel', 'Kuldeep Yadav']
    df['bowler_type'] = df['bowler'].apply(
        lambda x: 'Left-Arm Spin' if x in left_arm_spinners else 'Others'
    )

    return df

df = clean_data(df)
print("✅ Data cleaned and prepared!")

def calculate_run_rate_by_phase(df, team):
    """Calculate run rate for each phase"""
    team_data = df[df['batting_team'] == team]

    phase_stats = team_data.groupby('phase').agg({
        'total_runs': 'sum',
        'ball': 'count'
    }).reset_index()

    phase_stats['run_rate'] = (phase_stats['total_runs'] / phase_stats['ball']) * 6
    return phase_stats

def calculate_player_matchup(df, player, bowler_type='Left-Arm Spin'):
    """Calculate player performance against specific bowler type"""
    player_data = df[(df['batter'] == player) & (df['bowler_type'] == bowler_type)]

    if len(player_data) == 0:
        return None

    stats = {
        'balls_faced': len(player_data),
        'runs_scored': player_data['runs_off_bat'].sum(),
        'dismissals': player_data['is_wicket'].sum(),
        'strike_rate': (player_data['runs_off_bat'].sum() / len(player_data)) * 100 if len(player_data) > 0 else 0,
        'dismissal_rate': (player_data['is_wicket'].sum() / len(player_data)) * 100 if len(player_data) > 0 else 0
    }

    return stats

def get_top_batters(df, team, n=5):
    """Get top batters for a team"""
    team_data = df[df['batting_team'] == team]

    batter_stats = team_data.groupby('batter').agg({
        'runs_off_bat': 'sum',
        'ball': 'count',
        'is_wicket': 'sum'
    }).reset_index()

    batter_stats['strike_rate'] = (batter_stats['runs_off_bat'] / batter_stats['ball']) * 100
    batter_stats = batter_stats[batter_stats['ball'] >= 30]  # Minimum 30 balls
    batter_stats = batter_stats.sort_values('runs_off_bat', ascending=False).head(n)

    return batter_stats

def plot_phase_comparison(df, team1, team2):
    """Compare run rates across phases"""
    team1_stats = calculate_run_rate_by_phase(df, team1)
    team2_stats = calculate_run_rate_by_phase(df, team2)

    fig = go.Figure()

    fig.add_trace(go.Bar(
        name=team1,
        x=team1_stats['phase'],
        y=team1_stats['run_rate'],
        marker_color='#FDB913'
    ))

    fig.add_trace(go.Bar(
        name=team2,
        x=team2_stats['phase'],
        y=team2_stats['run_rate'],
        marker_color='#004BA0'
    ))

    fig.update_layout(
        title=f'Run Rate Comparison: {team1} vs {team2}',
        xaxis_title='Phase',
        yaxis_title='Run Rate',
        barmode='group',
        template='plotly_white',
        height=500
    )

    return fig

def plot_matchup_heatmap(df, team, bowler_type='Left-Arm Spin'):
    """Create heatmap for player matchups"""
    batters = get_top_batters(df, team, n=5)['batter'].tolist()

    data = []
    for batter in batters:
        stats = calculate_player_matchup(df, batter, bowler_type)
        if stats:
            data.append({
                'Batter': batter,
                'Strike Rate': stats['strike_rate'],
                'Dismissal %': stats['dismissal_rate']
            })

    if not data:
        return None

    matchup_df = pd.DataFrame(data)

    fig = make_subplots(
        rows=1, cols=2,
        subplot_titles=('Strike Rate', 'Dismissal %'),
        specs=[[{'type': 'bar'}, {'type': 'bar'}]]
    )

    fig.add_trace(
        go.Bar(x=matchup_df['Batter'], y=matchup_df['Strike Rate'],
               marker_color='lightgreen', name='Strike Rate'),
        row=1, col=1
    )

    fig.add_trace(
        go.Bar(x=matchup_df['Batter'], y=matchup_df['Dismissal %'],
               marker_color='salmon', name='Dismissal %'),
        row=1, col=2
    )

    fig.update_layout(
        title_text=f'Player Matchups vs {bowler_type}',
        showlegend=False,
        height=500,
        template='plotly_white'
    )

    return fig

def plot_runs_distribution(df, team):
    """Plot runs distribution by shot type"""
    team_data = df[df['batting_team'] == team]
    runs_dist = team_data['runs_off_bat'].value_counts().sort_index()

    fig = go.Figure(data=[
        go.Pie(labels=runs_dist.index, values=runs_dist.values, hole=0.3)
    ])

    fig.update_layout(
        title=f'Runs Distribution - {team}',
        template='plotly_white',
        height=400
    )

    return fig

teams = sorted(df['batting_team'].unique())

# Create widgets
team1_dropdown = widgets.Dropdown(
    options=teams,
    value=teams[0] if len(teams) > 0 else None,
    description='Team 1:',
    style={'description_width': 'initial'}
)

team2_dropdown = widgets.Dropdown(
    options=teams,
    value=teams[1] if len(teams) > 1 else teams[0],
    description='Team 2:',
    style={'description_width': 'initial'}
)

bowler_type_dropdown = widgets.Dropdown(
    options=['Left-Arm Spin', 'Others'],
    value='Left-Arm Spin',
    description='Bowler Type:',
    style={'description_width': 'initial'}
)

generate_button = widgets.Button(
    description='Generate Dashboard',
    button_style='success',
    icon='chart-bar'
)

output = widgets.Output()

def generate_dashboard(b):
    """Generate all visualizations"""
    with output:
        output.clear_output()

        print("🏏 IPL TEAM PERFORMANCE DASHBOARD 🏏")
        print("=" * 60)

        team1 = team1_dropdown.value
        team2 = team2_dropdown.value
        bowler_type = bowler_type_dropdown.value

        # Phase Comparison
        print(f"\n📊 Phase Analysis: {team1} vs {team2}")
        fig1 = plot_phase_comparison(df, team1, team2)
        fig1.show()

        # Matchup Analysis - Team 1
        print(f"\n🎯 Player Matchups - {team1} vs {bowler_type}")
        fig2 = plot_matchup_heatmap(df, team1, bowler_type)
        if fig2:
            fig2.show()
        else:
            print(f"No data available for {team1} vs {bowler_type}")

        # Matchup Analysis - Team 2
        print(f"\n🎯 Player Matchups - {team2} vs {bowler_type}")
        fig3 = plot_matchup_heatmap(df, team2, bowler_type)
        if fig3:
            fig3.show()
        else:
            print(f"No data available for {team2} vs {bowler_type}")

        # Runs Distribution
        print(f"\n📈 Runs Distribution Comparison")
        fig4 = plot_runs_distribution(df, team1)
        fig4.show()

        fig5 = plot_runs_distribution(df, team2)
        fig5.show()

        print("\n✅ Dashboard generated successfully!")

generate_button.on_click(generate_dashboard)

# Display dashboard controls
display(HTML("<h2>🏏 IPL Team Performance Dashboard</h2>"))
display(HTML("<p>Select two teams to compare their performance across different phases and matchups.</p>"))
display(widgets.VBox([team1_dropdown, team2_dropdown, bowler_type_dropdown, generate_button, output]))

print("\n" + "="*60)
print("✅ Dashboard is ready! Select teams and click 'Generate Dashboard'")
print("="*60)